# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1
orbs:
# Use a package of configuration called an orb.
  node: circleci/node@1.1.0

# define job
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
          # install mocha testing framework and other relevant packages
            - run: npm install mocha
            - run: alias mocha='./node_modules/.bin/_mocha'
            - run: npm install
            - run: npm run-script install-all
      - run:
          #start server
          command: npm run-script dev
          background: true
      # wait for server then run server.test.js
      - run: sleep 30
      - run: npm run test
